apiVersion: v1
entries:
  cmc:
  - apiVersion: v1
    appVersion: V.0.1
    created: "2020-07-21T09:03:42.6900285Z"
    description: '&#039;Naast deze JSON rest API is er ook een [graphql](/graphql)
      interface beschikbaar.&#039;'
    digest: 5f13a49930908ab52db0d6bc8e049a537f1edb9af59a9ffe6c1c67ffb36931d1
    home: cmc.zaakonline.nl
    icon: cmc.zaakonline.nl
    name: cmc
    urls:
    - cmc-0.1.0.tgz
    version: 0.1.0
generated: "2020-07-21T09:03:42.6803589Z"
